import {
  FileText, Map, Calculator, MessageCircle, Repeat, ArrowRight, Check,
  Clock, ShieldCheck, Smartphone, Palette, Sparkles, MousePointerClick,
  LayoutDashboard, FilePlus2, Users, Wrench, CreditCard, Settings,
  Menu, X, ChevronDown, Search, Filter, Plus, Download, Share2,
  Eye, EyeOff, Copy, Edit3, Trash2, AtSign, Globe, Link2,
  Rss, Mountain, Compass, Star, TrendingUp, Bell, LogOut,
  UploadCloud, AlertCircle, CheckCircle2, Info, XCircle,
} from "lucide-react";

const ICONS = {
  "file-text": FileText,
  map: Map,
  calculator: Calculator,
  "message-circle": MessageCircle,
  repeat: Repeat,
  "arrow-right": ArrowRight,
  check: Check,
  clock: Clock,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  palette: Palette,
  sparkles: Sparkles,
  "mouse-pointer-click": MousePointerClick,
  dashboard: LayoutDashboard,
  "file-plus": FilePlus2,
  users: Users,
  wrench: Wrench,
  "credit-card": CreditCard,
  settings: Settings,
  menu: Menu,
  close: X,
  "chevron-down": ChevronDown,
  search: Search,
  filter: Filter,
  plus: Plus,
  download: Download,
  share: Share2,
  eye: Eye,
  "eye-off": EyeOff,
  copy: Copy,
  edit: Edit3,
  trash: Trash2,
  instagram: AtSign,
  facebook: Globe,
  twitter: Rss,
  linkedin: Link2,
  mountain: Mountain,
  compass: Compass,
  star: Star,
  "trending-up": TrendingUp,
  bell: Bell,
  logout: LogOut,
  upload: UploadCloud,
  "alert-circle": AlertCircle,
  "check-circle": CheckCircle2,
  info: Info,
  "x-circle": XCircle,
};

export default function Icon({ name, size = 20, strokeWidth = 1.8, className = "" }) {
  const Cmp = ICONS[name] || Info;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}
